In [1]:
import torch
print(torch.__version__)

2.6.0+cpu


## Introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[1, 1]

tensor(10)

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

Why Random Tensors?

Random Tensors are the important because the way namy neural networks learn is that they start with tensors full of random numbers and then adjust thise random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update data`

In [20]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6542, 0.1278, 0.0412, 0.1643],
        [0.7416, 0.1014, 0.4366, 0.3166],
        [0.4050, 0.8700, 0.6540, 0.5359]])

In [21]:
random_tensor.ndim

2

In [27]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)