In [72]:
import torch
print(torch.__version__)

2.6.0+cpu


## Introduction to Tensors

### Creating tensors

In [73]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [74]:
scalar.ndim

0

In [75]:
# get tensor back as python int
scalar.item()

7

In [76]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [77]:
vector.ndim

1

In [78]:
vector.shape

torch.Size([2])

In [79]:
# MATRIX
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [80]:
matrix.ndim

2

In [81]:
matrix[1, 1]

tensor(10)

In [82]:
matrix.shape

torch.Size([2, 2])

In [83]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [84]:
tensor.ndim

3

In [85]:
tensor.shape

torch.Size([1, 3, 3])

In [86]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

Why Random Tensors?

Random Tensors are the important because the way namy neural networks learn is that they start with tensors full of random numbers and then adjust thise random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update data`

In [87]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5673, 0.8018, 0.1505, 0.2687],
        [0.3726, 0.5322, 0.2450, 0.6505],
        [0.3966, 0.6674, 0.1613, 0.4965]])

In [88]:
random_tensor.ndim

2

In [89]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [90]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [91]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range and tensors-like

In [92]:
# use torch.arange()
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
# Creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [94]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.01],
                               dtype=None, # datatype
                               device='cpu',
                               requires_grad=False)
float_32_tensor.dtype, float_32_tensor

(torch.float32, tensor([3.0000, 6.0000, 9.0100]))

In [95]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype, float_16_tensor

(torch.float16, tensor([3.0000, 6.0000, 9.0078], dtype=torch.float16))

In [96]:
float_16_tensor * float_32_tensor

tensor([ 9.0000, 36.0000, 81.1604])

In [97]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [98]:
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_64_tensor

tensor([3, 6, 9])

### Getting information from tensors

In [99]:
some_tensor = torch.rand(3, 4)
some_tensor, some_tensor.dtype, some_tensor.shape, some_tensor.device

(tensor([[0.2633, 0.1585, 0.1247, 0.9186],
         [0.0391, 0.9935, 0.3777, 0.7955],
         [0.4174, 0.3968, 0.2851, 0.5811]]),
 torch.float32,
 torch.Size([3, 4]),
 device(type='cpu'))

### Manipulating tensors

Tensor Operations Include:
* Addition
* Subtract
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [100]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [101]:
tensor * 100

tensor([100, 200, 300])

In [102]:
tensor

tensor([1, 2, 3])

In [103]:
tensor - 10

tensor([-9, -8, -7])

In [104]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication

There are two main rules that performainh matrix multiplication needs to satisfy:
* `(3, 2) @ (3, 2)` won't work
* `(3, 2) @ (2, 3)` will work
* `(2, 3) @ (3, 2)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [105]:
# Element wise multiplication
print(tensor,"*",tensor,"=",tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [106]:
# M<atrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [107]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B.T) # torch.mm is the same as torch.matmul 
# to fix the tensor shape issues we can "transpose the matrix" to make it multiply

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [108]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [109]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [110]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [111]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [112]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [113]:
# Find the mean: the torch.mean(), function requires a tensor of float32 datatype,
# so x.mean() is not working
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [114]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [115]:
# find the position of the minimum value in a tensor
x.argmin()

tensor(0)

In [116]:
#Find the position in a tensor with max value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Reture a view of an input tensor of certain shape but keep the same memory
* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeexe - removes al `1` dimensions from a tensor
* Unqueeze - add a `1` dimension to a target tensor
* Premute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [117]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [118]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [119]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [120]:
# Changinng z changes x because a view of a tensor shares the same memory as the original
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [125]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [141]:
x_reshaped, x_reshaped.size()

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [142]:
x_squeeze = torch.squeeze(x_reshaped)
x_squeeze, x_squeeze.size()

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [148]:
x_original = torch.rand(1, 2, 3)

# permute it
x_permuted = x_original.permute(2, 1, 0)
x_original.shape, x_permuted.shape

(torch.Size([1, 2, 3]), torch.Size([3, 2, 1]))